project_id = "nhbumxmvtzuddribooks"

[functions.auto-clock-out]
verify_jwt = false

[functions.generate-salary-pdf]
verify_jwt = false

[functions.send-salary-email]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.generate-attendance-pdf]
verify_jwt = false

[functions.send-shoot-reminders]
verify_jwt = false

[functions.generate-report-pdf]
verify_jwt = false
